/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package letsPlay;

import java.awt.CardLayout;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.math.BigDecimal;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import javax.swing.SwingWorker;
import java.util.ArrayList;
import java.util.Date;
import java.text.DateFormat;
import mathisfun.MathIsFun;

/**
 *
 * @author Brooklyn
 */
public class LetsPlayGUI extends javax.swing.JFrame {

    /**
     * Creates new form LetsPlayGUI
     */
    public LetsPlayGUI() {
        super("Let's Play!");
        initComponents();
        setCardLayouts();
        showSplashPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        letsPlayPanel = new javax.swing.JPanel();
        splash = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        login = new javax.swing.JPanel();
        loginScrollPanel = new javax.swing.JScrollPane();
        loginOutputArea = new javax.swing.JTextArea();
        loginButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        userNameField = new javax.swing.JTextField();
        guestButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mathIsFun = new javax.swing.JPanel();
        mathIsFunMode = new javax.swing.JPanel();
        additionButton = new javax.swing.JButton();
        subtractionButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        mathIsFunDifficulty = new javax.swing.JPanel();
        easyButton = new javax.swing.JButton();
        mediumButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        mathIsFunOptions = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        precisionSelection = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        mathIsFunGame = new javax.swing.JPanel();
        game = new javax.swing.JPanel();
        questions = new javax.swing.JPanel();
        equationLine = new javax.swing.JSeparator();
        topNumber = new javax.swing.JLabel();
        bottomNumber = new javax.swing.JLabel();
        playerAnswerField = new javax.swing.JTextField();
        operatorField = new javax.swing.JLabel();
        answers = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        terminal = new javax.swing.JPanel();
        submitButton = new javax.swing.JToggleButton();
        terminalInputField = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        terminalOutputField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setAutoscrolls(true);
        mainPanel.setLayout(new java.awt.CardLayout());

        letsPlayPanel.setLayout(new java.awt.CardLayout());

        splash.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/splashImage.png"))); // NOI18N

        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout splashLayout = new javax.swing.GroupLayout(splash);
        splash.setLayout(splashLayout);
        splashLayout.setHorizontalGroup(
            splashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splashLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, splashLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        splashLayout.setVerticalGroup(
            splashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splashLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        letsPlayPanel.add(splash, "splash");

        loginOutputArea.setEditable(false);
        loginOutputArea.setColumns(20);
        loginOutputArea.setRows(5);
        loginScrollPanel.setViewportView(loginOutputArea);

        loginButton.setText("Next");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        passwordField.setText("jPasswordField1");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        userNameField.setText("username");
        userNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFieldFocusGained(evt);
            }
        });

        guestButton.setText("Guest");
        guestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Warning: Scores will not be saved in guest mode.");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(loginScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 107, Short.MAX_VALUE))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(loginScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        letsPlayPanel.add(login, "login");

        mainPanel.add(letsPlayPanel, "letsPlayPanel");

        mathIsFun.setLayout(new java.awt.CardLayout());

        additionButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        additionButton.setText("ADDITION");
        additionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionButtonActionPerformed(evt);
            }
        });

        subtractionButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subtractionButton.setText("SUBTRACTION");
        subtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionButtonActionPerformed(evt);
            }
        });

        divisionButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        divisionButton.setText("DIVISION");
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });

        multiplicationButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        multiplicationButton.setText("MULTIPLICATION");
        multiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mathIsFunModeLayout = new javax.swing.GroupLayout(mathIsFunMode);
        mathIsFunMode.setLayout(mathIsFunModeLayout);
        mathIsFunModeLayout.setHorizontalGroup(
            mathIsFunModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mathIsFunModeLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(mathIsFunModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(additionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(multiplicationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mathIsFunModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subtractionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(divisionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140))
        );
        mathIsFunModeLayout.setVerticalGroup(
            mathIsFunModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mathIsFunModeLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(mathIsFunModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(additionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(subtractionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(mathIsFunModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );

        mathIsFun.add(mathIsFunMode, "mode");

        easyButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        easyButton.setText("EASY");
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });

        mediumButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mediumButton.setText("MEDIUM");
        mediumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumButtonActionPerformed(evt);
            }
        });

        hardButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hardButton.setText("HARD");
        hardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mathIsFunDifficultyLayout = new javax.swing.GroupLayout(mathIsFunDifficulty);
        mathIsFunDifficulty.setLayout(mathIsFunDifficultyLayout);
        mathIsFunDifficultyLayout.setHorizontalGroup(
            mathIsFunDifficultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mathIsFunDifficultyLayout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addGroup(mathIsFunDifficultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mediumButton, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(hardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(easyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(291, 291, 291))
        );
        mathIsFunDifficultyLayout.setVerticalGroup(
            mathIsFunDifficultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mathIsFunDifficultyLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(easyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(mediumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(hardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        mathIsFun.add(mathIsFunDifficulty, "difficulty");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("How many questions would you like?");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("How many decimal places?");

        javax.swing.GroupLayout precisionSelectionLayout = new javax.swing.GroupLayout(precisionSelection);
        precisionSelection.setLayout(precisionSelectionLayout);
        precisionSelectionLayout.setHorizontalGroup(
            precisionSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precisionSelectionLayout.createSequentialGroup()
                .addGroup(precisionSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(precisionSelectionLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4))
                    .addGroup(precisionSelectionLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        precisionSelectionLayout.setVerticalGroup(
            precisionSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precisionSelectionLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addGap(46, 46, 46)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mathIsFunOptionsLayout = new javax.swing.GroupLayout(mathIsFunOptions);
        mathIsFunOptions.setLayout(mathIsFunOptionsLayout);
        mathIsFunOptionsLayout.setHorizontalGroup(
            mathIsFunOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mathIsFunOptionsLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mathIsFunOptionsLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(mathIsFunOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(precisionSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 186, Short.MAX_VALUE))
        );
        mathIsFunOptionsLayout.setVerticalGroup(
            mathIsFunOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mathIsFunOptionsLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(precisionSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        mathIsFun.add(mathIsFunOptions, "card4");

        game.setLayout(new java.awt.CardLayout());

        equationLine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        topNumber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        bottomNumber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        playerAnswerField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        operatorField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout questionsLayout = new javax.swing.GroupLayout(questions);
        questions.setLayout(questionsLayout);
        questionsLayout.setHorizontalGroup(
            questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(operatorField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(playerAnswerField)
                    .addComponent(topNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(equationLine)
                    .addComponent(bottomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addGap(259, 259, 259))
        );
        questionsLayout.setVerticalGroup(
            questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsLayout.createSequentialGroup()
                .addComponent(topNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bottomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatorField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(equationLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        game.add(questions, "card2");

        javax.swing.GroupLayout answersLayout = new javax.swing.GroupLayout(answers);
        answers.setLayout(answersLayout);
        answersLayout.setHorizontalGroup(
            answersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        answersLayout.setVerticalGroup(
            answersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        game.add(answers, "card3");

        javax.swing.GroupLayout mathIsFunGameLayout = new javax.swing.GroupLayout(mathIsFunGame);
        mathIsFunGame.setLayout(mathIsFunGameLayout);
        mathIsFunGameLayout.setHorizontalGroup(
            mathIsFunGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mathIsFunGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(game, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mathIsFunGameLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mathIsFunGameLayout.setVerticalGroup(
            mathIsFunGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mathIsFunGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(game, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        mathIsFun.add(mathIsFunGame, "card5");

        mainPanel.add(mathIsFun, "mathIsFunPanel");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        terminalInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminalInputFieldActionPerformed(evt);
            }
        });

        terminalOutputField.setEditable(false);
        terminalOutputField.setColumns(20);
        terminalOutputField.setRows(5);
        scrollPane.setViewportView(terminalOutputField);

        javax.swing.GroupLayout terminalLayout = new javax.swing.GroupLayout(terminal);
        terminal.setLayout(terminalLayout);
        terminalLayout.setHorizontalGroup(
            terminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(terminalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(terminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane)
                    .addComponent(terminalInputField))
                .addContainerGap())
            .addGroup(terminalLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        terminalLayout.setVerticalGroup(
            terminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(terminalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(terminalInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(terminal, "terminalPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        userInput = terminalInputField.getText();
        terminalInputField.setText("");
    }//GEN-LAST:event_submitButtonActionPerformed

    private void terminalInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminalInputFieldActionPerformed
        submitButtonActionPerformed(evt);
    }//GEN-LAST:event_terminalInputFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        flag = true;
        (new CheckRegistry()).execute();
        synchronized(LOCK){
            do{
                try{
                    LOCK.wait(1000);
                }catch(InterruptedException e){
                    //do nothing
                }
            }while(flag);
        }
        if(registryAvailable == false){
            startGuestMode();
        }else {
            setLoginIO();
            showLoginPanel();
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        login();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void additionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionButtonActionPerformed
        showMIFDifficultyPanel();
        MathIsFun.setMode("ADDITION");
    }//GEN-LAST:event_additionButtonActionPerformed

    private void subtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionButtonActionPerformed
        showMIFDifficultyPanel();
        MathIsFun.setMode("SUBTRACTION");
    }//GEN-LAST:event_subtractionButtonActionPerformed

    private void multiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationButtonActionPerformed
        showMIFDifficultyPanel();
        MathIsFun.setMode("MULTIPLICATION");
    }//GEN-LAST:event_multiplicationButtonActionPerformed

    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonActionPerformed
        showMIFDifficultyPanel();
        MathIsFun.setMode("DIVISION");
    }//GEN-LAST:event_divisionButtonActionPerformed

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        MathIsFun.setDifficulty("EASY");
        setTerminalIO();
        showTerminalPanel();
        (new MathIsFunGame()).execute();
    }//GEN-LAST:event_easyButtonActionPerformed

    private void mediumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumButtonActionPerformed
        MathIsFun.setDifficulty("MEDIUM");
        setTerminalIO();
        showTerminalPanel();
        (new MathIsFunGame()).execute();
    }//GEN-LAST:event_mediumButtonActionPerformed

    private void hardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButtonActionPerformed
        MathIsFun.setDifficulty("HARD");
        setTerminalIO();
        showTerminalPanel();
        (new MathIsFunGame()).execute();
    }//GEN-LAST:event_hardButtonActionPerformed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        int key = evt.getKeyCode();
        if (key == java.awt.event.KeyEvent.VK_ENTER) {
           login();
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    private void userNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFieldFocusGained
        userNameField.selectAll();
    }//GEN-LAST:event_userNameFieldFocusGained

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        passwordField.selectAll();
    }//GEN-LAST:event_passwordFieldFocusGained

    private void guestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestButtonActionPerformed
        startGuestMode();
    }//GEN-LAST:event_guestButtonActionPerformed
    private void startGuestMode(){
        firstName = "Guest";
        (new MathIsFunGame()).execute();
    }
    private void login(){
        System.out.println("Verifying...");
        Utilities.verifyUserName(userNameField.getText());
        Utilities.verifyPassword(passwordField.getPassword());
        isValid = Utilities.login();
        if(isValid){
            firstName = Utilities.getFirstName();
            showMIFModePanel();
        }else{
            System.out.println("Incorrect username or password. Try again.");
            userNameField.setText("Username");
            passwordField.setText("password");
        }
    }
    private class CheckRegistry extends SwingWorker<Integer, String>{
        @Override
        protected Integer doInBackground(){
            registryAvailable = Utilities.findRegistry();
            if(registryAvailable == false){
                int answer = Utilities.showOptionDialog("Error: Registry.txt is missing. Game information will not be saved. Continue in guest mode?");
                if(answer == 1){
                    Utilities.showErrorDialog("Fatal Error: Registry.txt is missing.");
                }
            }
            flag = false;
            return 1;
        }
    }
    private class MathIsFunGame extends SwingWorker<Integer, String>{
        @Override
        protected Integer doInBackground(){
            boolean playAgain = MathIsFun.startGame(firstName);
            if(playAgain){
                showMIFModePanel();
                terminalOutputField.setText("");
            }else{
                dispose();
                if(!firstName.equals("Guest")){
                    saveGameData();
                }
            }
            return 1;
        }
    }
    
    private void setCardLayouts(){
        mainPanelLayoutManager = (CardLayout) mainPanel.getLayout();
        mathIsFunLayoutManager = (CardLayout) mathIsFun.getLayout();
        letsPlayLayoutManager = (CardLayout) letsPlayPanel.getLayout();
    }
    private void setTerminalIO(){
        printStream = new PrintStream(new Utilities().new CustomOutputStream(terminalOutputField));
        System.setOut(printStream);
        System.setErr(printStream);
    }
    private void setLoginIO(){
        printStream = new PrintStream(new Utilities().new CustomOutputStream(loginOutputArea));
        System.setOut(printStream);
        System.setErr(printStream);
        System.out.println("Please enter your username and password.");
    }
    private void saveGameData(){
        ArrayList<BigDecimal> scores = LetsPlay.getScores();
        ArrayList<String> games = LetsPlay.getGames();
        Date date = new Date();
        DateFormat dateFormat = DateFormat.getDateInstance();
        String today = dateFormat.format(date);
        today = String.format("%s%n", today);
        Path studentFile = Utilities.getStudentFile();
        try(BufferedWriter bw = Files.newBufferedWriter(studentFile, Charset.defaultCharset(), StandardOpenOption.WRITE, StandardOpenOption.APPEND)){
            bw.write(today);
            for(int i = 0; i<scores.size(); i++){
                String message = String.format("%s\t%s%%%n", games.get(i), scores.get(i));
                bw.write(message);
            }
        }catch(IOException e){
            Utilities.showErrorDialog("Fatal error: Unable to save student data to file.", e);
        }
    }
    public static String getUserInput(){
        String input;
        while(userInput == null){
            synchronized(LOCK){
                try{
                    LOCK.wait(1000);
                }catch(InterruptedException e){
                    e.printStackTrace();
                }
            }
        }
        input = userInput;
        userInput = null;
        return input;
    }
    private void showTerminalPanel(){
        mainPanelLayoutManager.show(mainPanel, "terminalPanel");
    }
    private void showLoginPanel(){
        mainPanelLayoutManager.show(mainPanel, "letsPlayPanel");
        letsPlayLayoutManager.show(letsPlayPanel, "login");
    }
    private void showSplashPanel(){
        mainPanelLayoutManager.show(mainPanel, "letsPlayPanel");
        letsPlayLayoutManager.show(letsPlayPanel, "splash");
    }
    private void showMIFModePanel(){
        mainPanelLayoutManager.show(mainPanel, "mathIsFunPanel");
        mathIsFunLayoutManager.show(mathIsFun, "mode");
    }
    private void showMIFDifficultyPanel(){
        mainPanelLayoutManager.show(mainPanel, "mathIsFunPanel");
        mathIsFunLayoutManager.show(mathIsFun, "difficulty");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LetsPlayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LetsPlayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LetsPlayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LetsPlayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LetsPlayGUI().setVisible(true);
            }
        });
        
    }
    
    //Class Variables
    private PrintStream printStream;
    private static String userInput;
    public static final String LOCK = "lock";
    private static String firstName;
    private Boolean registryAvailable;
    private Boolean isValid;
    private Boolean flag;
    private Boolean isRunning;
    private CardLayout mainPanelLayoutManager;
    private CardLayout mathIsFunLayoutManager;
    private CardLayout letsPlayLayoutManager;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionButton;
    private javax.swing.JPanel answers;
    private javax.swing.JLabel bottomNumber;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton easyButton;
    private javax.swing.JSeparator equationLine;
    private javax.swing.JPanel game;
    private javax.swing.JButton guestButton;
    private javax.swing.JButton hardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel letsPlayPanel;
    private javax.swing.JPanel login;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextArea loginOutputArea;
    private javax.swing.JScrollPane loginScrollPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mathIsFun;
    private javax.swing.JPanel mathIsFunDifficulty;
    private javax.swing.JPanel mathIsFunGame;
    private javax.swing.JPanel mathIsFunMode;
    private javax.swing.JPanel mathIsFunOptions;
    private javax.swing.JButton mediumButton;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JLabel operatorField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField playerAnswerField;
    private javax.swing.JPanel precisionSelection;
    private javax.swing.JPanel questions;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel splash;
    private javax.swing.JButton startButton;
    private javax.swing.JToggleButton submitButton;
    private javax.swing.JButton subtractionButton;
    private javax.swing.JPanel terminal;
    private javax.swing.JTextField terminalInputField;
    private javax.swing.JTextArea terminalOutputField;
    private javax.swing.JLabel topNumber;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
